### ISSUE TITLE
New version of Blue Archive doesn't have MediaCatalog.json

### ISSUE THREAD

**Issue by TaroKid** [Endergreen12/Blue-Archive-Assets-Converter#1]
I found out that the json file stopped updating since last month(3/27), so I tried reinstall the game.
After I downloaded the resources, I can't find json file in MediaPatch folder.
先月(3/27)からjsonファイルの更新が止まっていることが分かり、ゲームを再インストールしてみました。
リソースをダウンロードした後、MediaPatch フォルダーに json ファイルが見つかりません。(Sorry for using translator)
Is there any solution been found?
![螢幕擷取畫面 2024-04-29 102728](https://github.com/Endergreen12/Blue-Archive-Assets-Converter/assets/109242735/34d60ed9-e927-4f4c-bc76-508ce5268068)

**Comment by Endergreen12** [comment]
調べてみると、どうやらMediaCatalog.jsonがバイナリに変換されてMediaCatalog.bytesに保存されているようです。
Upon examination, it appears that MediaCatalog.json is converted to binary and stored in MediaCatalog.bytes

![image](https://github.com/Endergreen12/Blue-Archive-Assets-Converter/assets/90076182/7479fe8c-7d6a-4b36-88ab-a9c2b5d9bcad)

MediaCatalog.jsonにあった情報はMediaCatalog.bytesでもバイナリとしてそのまま保存されているようなので、コードを書き直せばまたこのツールは機能するようになると思います。
The information that was in MediaCatalog.json seems to be preserved as binary in MediaCatalog.bytes, so if I rewrite the code, this tool will work again

ですが、自分はバイナリについて全く知識がなく、またほぼコードを書き直すことになるので、かなり時間がかかると思います。
However, I have no knowledge of binaries and I would have to rewrite almost all of the code, which would take a lot of time

とりあえず今からバイナリについて調べながらコードを書き直してみます。
In the meantime, I'm going to rewrite the code now, looking into binaries

ご報告ありがとうございました。
Thank you for your report

**Comment by Endergreen12** [comment]
After I replied, I thought, maybe there is no MediaCatalog.bytes either?
I haven't reinstalled the blue archive myself, so I haven't figured out which files are missing yet...

**Comment by TaroKid** [comment]
I think the game automatically created the bytes file and kill it after the game reading completed.
If I close the game before the game stop loading, the bytes file will remain.

**Comment by Endergreen12** [comment]
i reinstalled the Blue Archive and confirmed that fact
i'm trying to find out where the game is getting the MediaCatalog.bytes from,
but if it's hard-coded, i don't have the technology to parse it, so i'm out of luck
worst case scenario, we'll have to make the user take that step to use this app
